import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/sonner";

/**
 * Root Layout (Server Component)
 *
 * Applies to all pages under /src/app.
 * Exports the layout and metadata
 *
 * Responsibilities:
 * - Declare fonts / global styles
 * - Define the <html> / <body> structure
 * - Mount global providers (Toaster)
 */

// ======================================================
// Global Fonts
// ======================================================
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ======================================================
// Global Metadata
// ======================================================
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ======================================================
// Layout
// ======================================================
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        {children}
        <Toaster position="top-right"/>
      </body>
    </html>
  );
}
